### ISSUE TITLE
How the dataset comes？ 

### ISSUE THREAD

**Issue by Ting-Bao** [Anupam-Bh/ML_2D_flat_band#1]
The Materials Project doesn't provide a tag of whether the band is flat, is all the flat band data tagged manually?
In your excellent arxiv article, it says the model is tested on 7000 band images segments but the training process uses only 1900 materials, why not to enlarge the training set? 
Many thanks！

**Comment by Anupam-Bh** [comment]
Sorry for replying late. 
Yes, band flatness is tagged manually. 
Each material project band-structure image is divided into segments and one has to click on the positive segments (as implemented in the Matlab code). This will save the unclicked segments as negative examples. Doing this for the 1900 band structures was a bit cumbersome but quite straightforward. After dividing the images, the dataset becomes quite large.

Later, while using the model for prediction, one can get an estimate of the bandwidth (for a band) that the algorithm would mark flat for a chosen classification threshold.

**Comment by Ting-Bao** [comment]
Thank you very much for replying!
